### ISSUE TITLE
BUG when compiling

### ISSUE THREAD

**Issue by crashzk** [KewaiiGamer/Store-Roulette#4]
I'm trying to compile the plugin, but the following appears in the BUG:
http://prntscr.com/jh3qx1

The change in question would just remove your name from the TAG, leave only Roleta.

It would be possible?

**Comment by crashzk** [comment]
Problem solved, thank you!

**Comment by KewaiiGamer** [comment]
Even though this issue is already closed I must say that those errors was nowhere related to what you said in steam PM. This is an issue with one of your includes namely handles.inc
