### ISSUE TITLE
KewaiiGamer/Store-Roulette

### ISSUE THREAD

**Issue by ghost** [KewaiiGamer/Store-Roulette#6]
I use HexTags ... My "VIP" clantag has the "o" flag ....
No admins.simple.ini meti

"(Steam Id)" "o"

When I enter the game he doesn't have access to the "VIP" at the roulette ... Do you know what I can do?

Have a good afternoon

**Comment by KewaiiGamer** [comment]
the "o"  flag is a custom flag and not supposed to be used as a VIP flag. the default flag for vip is "a" (slot reservation flag). you can either change the convar to use the flag you use or add the "a" flag to your VIP group permissions (which should be added already anyway)

**Comment by ghost** [comment]
Yes, I noticed yesterday that a flag for the VIP is an A ... Tell me, is it possible to decrease the chance of winning?

**Comment by KewaiiGamer** [comment]
I will be closing this ticket as I already helped you over Discord.
